import type { NextPage } from "next";
import Head from "next/head";

import { useGetDrabantsQuery } from "../store/features/drabant";

import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  const { data: drabants } = useGetDrabantsQuery();

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {drabants?.map((drabant) => drabant.name)}
      </main>
    </div>
  );
};

export default Home;
